export const LANDING_COPY = {
  nav: {
    wordmark: 'MINDBLOOM',
    links: ['EXPLORE', 'ABOUT', 'RESOURCES', 'SIGN IN'] as const,
  },
  s01: {
    number: '01',
    label: 'INTRO',
    headline: "You don't have to\nhave it all figured out.",
    body: 'A quiet digital space for students to pause,\nreflect, find support, and take the next small step.',
    cta: 'ENTER MINDBLOOM',
    scrollHint: 'SCROLL',
  },
  s02: {
    number: '02',
    label: 'THE FEELING',
    headline: 'Some days,\neverything feels\nlike too much.',
    pills: ['DEADLINES', 'EXPECTATIONS', 'LONELINESS', 'UNCERTAINTY', 'PRESSURE'] as const,
  },
  s03: {
    number: '03',
    label: 'OUR SPACE',
    headline: 'So we made a place\nto put some of it down.',
    body: "MindBloom is more than an app.\nIt's a space that understands,\nsupports, and grows with you.",
  },
  s04: {
    number: '04',
    label: 'TALK',
    headline: "Sometimes you\ndon't need an answer.\nYou just need\nsomewhere to talk.",
    body: 'Bloom is your AI companion\nwho listens, understands,\nand is here for you always.',
    chatName: 'Bloom',
    chatMessages: [
      { text: 'Hey, how are you feeling today?', sender: 'bloom' as const },
      { text: 'A little overwhelmed, honestly.', sender: 'user' as const },
      { text: "That's completely okay.\nWant to talk about it?", sender: 'bloom' as const },
    ],
    chatPlaceholder: 'Message Bloom...',
  },
  s05: {
    number: '05',
    label: 'REFLECT',
    headline: 'Give your thoughts\nsomewhere to grow.',
    body: 'Your journal becomes a tree.\nEvery thought, a leaf.\nEvery leaf, a part of your growth.',
    cta: 'EXPLORE JOURNAL',
  },
  s06: {
    number: '06',
    label: 'RESET',
    headline: 'Not everything\nneeds to be solved.',
    tagline: 'Take a breath. Play. Reset.',
    tools: ['BREATHE', 'FOCUS', 'UNWIND'] as const,
  },
  s07: {
    number: '07',
    label: 'DISCOVER',
    headline: 'Find what helps,\nwhen you need it.',
    cta: 'EXPLORE RESOURCES',
    moods: ['Overwhelmed', 'Anxious', 'Lonely', 'Unmotivated', 'Tired'] as const,
  },
  s08: {
    number: '08',
    label: 'PHILOSOPHY',
    quote: 'You are not something\nthat needs fixing.',
    brand: 'MINDBLOOM',
  },
  s09: {
    number: '09',
    label: 'HOW IT WORKS',
    steps: [
      { num: '01', title: 'CHECK IN', body: 'Start where you are.' },
      { num: '02', title: 'EXPLORE', body: 'Find what you need.' },
      { num: '03', title: 'REFLECT', body: 'Understand yourself\na little better.' },
      { num: '04', title: 'GROW', body: 'Take the next small\nstep forward.' },
    ] as const,
  },
  s10: {
    number: '10',
    label: 'SUPPORT',
    headline: 'Support should be accessible.\nAnd when you need more,\nhelp should be close.',
    body: "MindBloom is here for you, but it's okay to reach out\nto a real person too. You don't have to go through it alone.",
    cta: 'SUPPORT RESOURCES',
  },
  s11: {
    number: '11',
    label: 'BEGIN',
    body: 'A quiet space for students who need it.',
  },
} as const;
